# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Main"

on:
  push:
    tags: ["*"]
    branches: ["*"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:

permissions: {}

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
    container: "docker.io/alpine:latest"
    steps:
      - name: "Install packages"
        run: "apk add --no-cache build-base pkgconf"
      - name: "Checkout"
        uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683"
      - name: "Build"
        run: |
          make all STATIC=1
          strip -s ./udptunnel
          ./udptunnel --help
      - name: "Upload artifacts"
        uses: "actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882"
        with:
          name: "dist"
          path: "./udptunnel"
          retention-days: 1

  publish-github-release:
    name: "Publish GitHub release"
    if: "startsWith(github.ref, 'refs/tags/v')"
    needs: ["build"]
    runs-on: "ubuntu-latest"
    permissions:
      contents: "write"
    steps:
      - name: "Download artifacts"
        uses: "actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16"
        with:
          name: "dist"
          path: "assets"
      - name: "Publish"
        uses: "hectorm/ghaction-release@066200d04c3549852afa243d631ea3dc93390f68"
        with:
          assets-path: "./assets/"
