# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Main"

on:
  push:
    tags: ["*"]
    branches: ["*"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:

permissions: {}

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
    container: "docker.io/alpine:latest"
    steps:
      - name: "Install packages"
        run: "apk add --no-cache build-base pkgconf"
      - name: "Checkout"
        uses: "actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8"
      - name: "Build"
        run: |
          make all STATIC=1
          strip -s ./udptunnel
          ./udptunnel --help
      - name: "Upload artifacts"
        uses: "actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4"
        with:
          name: "dist"
          path: "./udptunnel"
          retention-days: 1

  publish-github-release:
    name: "Publish GitHub release"
    if: "startsWith(github.ref, 'refs/tags/v')"
    needs: ["build"]
    runs-on: "ubuntu-latest"
    permissions:
      contents: "write"
    steps:
      - name: "Download artifacts"
        uses: "actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53"
        with:
          name: "dist"
          path: "assets"
      - name: "Publish"
        uses: "hectorm/ghaction-release@d0426a7a369ce2c1ed615e1a583788b22745ccfe"
        with:
          assets-path: "./assets/"
